[build]
command = "npm run build"
publish = "_site"

[dev]
command = "npm run dev"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "_site/img/output", # Eleventy Image Disk Cache
    ".cache" # Remote Asset Cache
  ]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
