title: Mia Culpa
description: Art & CSS & other digital artifacts of my life
author: Miriam Eric Suzanne
feed: /feed.xml

sizes:
  default: '(min-width: 65em) 60vw, 95vw'
  hero: '(min-width: 75em) 75vw, 95vw'
  gallery: '(min-width: 65em) 30vw, (min-width: 30em) 45vw, 95vw'
  media: '(min-width: 65em) 15vw, (min-width: 30em) 30vw, 50vw'
  og: '1200px'
