title: Miriam Suzanne
description: >
  Art & CSS & other digital artifacts of my life
  as a hybrid creator/teacher based in Denver.
author: Miriam Eric Suzanne
domain: www.miriamsuzanne.com
feed: /feed.xml
og:
  src: _site/og.jpg
  alt: >
    Mia in sepia looking side-eye
    like what-the-fuck,
    with an overlay of her M stamp
    and miriamSuzanne.com
