backend:
  name: git-gateway
  branch: main
media_folder: "src/_assets/images/cms"
public_folder: "/cms/"

# Please run "npx static-cms-proxy-server" for local backend
# local_backend: true
collections:
  - name: posts # Used in routes, e.g., /admin/collections/blog
    label: Posts
    folder: 'src/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - name: layout
        widget: hidden
        default: page
      - name: title
      - name: date
        widget: datetime
      - name: hero
        widget: object
        summary: '{{fields.alt}}'
        collapsed: true
        fields:
          - name: img
            widget: image
          - name: alt
      - name: summary
        widget: text
      - name: body
        widget: markdown
